// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("capable_bpf")
            .map("events", false)
            .map("seen", false)
            .map("capable_.rodata", true)
            .map("capable_.bss", true)
            .prog("kprobe__cap_capable");
        builder.build()
    }
    pub struct OpenCapableMaps<'obj> {
        pub events: libbpf_rs::OpenMapMut<'obj>,
        pub seen: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        pub rodata_data: &'obj mut types::rodata,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: &'obj mut types::bss,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenCapableMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut seen = None;
            let mut rodata = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "seen" => seen = Some(map),
                    "capable_.rodata" => rodata = Some(map),
                    "capable_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                seen: seen.expect("map `seen` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_mut()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                        .expect("BPF map `bss` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct CapableMaps<'obj> {
        pub events: libbpf_rs::MapMut<'obj>,
        pub seen: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        pub rodata_data: &'obj types::rodata,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: &'obj mut types::bss,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> CapableMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut seen = None;
            let mut rodata = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "seen" => seen = Some(map),
                    "capable_.rodata" => rodata = Some(map),
                    "capable_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                seen: seen.expect("map `seen` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                rodata_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `rodata` does not have mmap pointer")
                        .cast::<types::rodata>()
                        .as_ref()
                        .expect("BPF map `rodata` mmap pointer is NULL")
                },
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                        .expect("BPF map `bss` mmap pointer is NULL")
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenCapableProgs<'obj> {
        pub kprobe__cap_capable: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenCapableProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut kprobe__cap_capable = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "kprobe__cap_capable" => kprobe__cap_capable = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                kprobe__cap_capable: kprobe__cap_capable
                    .expect("prog `kprobe__cap_capable` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct CapableProgs<'obj> {
        pub kprobe__cap_capable: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> CapableProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenCapableProgs<'obj>) -> Self {
            Self {
                kprobe__cap_capable: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.kprobe__cap_capable.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct CapableSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> CapableSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenCapableSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenCapableSkel {
                maps: unsafe { OpenCapableMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenCapableProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for CapableSkelBuilder {
        type Output = OpenCapableSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenCapableSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenCapableSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 4],
            pub key_size: *mut [i32; 4],
            pub value_size: *mut [i32; 4],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    key_size: std::ptr::null_mut(),
                    value_size: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct unique_key {
            pub cap: i32,
            pub tgid: u32,
            pub cgroupid: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 1],
            pub max_entries: *mut [i32; 10240],
            pub key: *mut unique_key,
            pub value: *mut u64,
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub __anon_3: __anon_3,
            pub orig_x0: u64,
            pub syscallno: i32,
            pub unused2: u32,
            pub sdei_ttbr1: u64,
            pub pmr_save: u64,
            pub stackframe: [u64; 2],
            pub lockdep_hardirqs: u64,
            pub exit_rcu: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_3 {
            pub user_regs: user_pt_regs,
            pub __anon_4: __anon_4,
        }
        impl std::fmt::Debug for __anon_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_3 {
            fn default() -> Self {
                Self {
                    user_regs: user_pt_regs::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct user_pt_regs {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_4 {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_5 {
            pub tgid: u32,
            pub verbose: std::mem::MaybeUninit<bool>,
            pub unique_type: std::mem::MaybeUninit<uniqueness>,
        }
        impl Default for __anon_5 {
            fn default() -> Self {
                Self {
                    tgid: u32::default(),
                    verbose: std::mem::MaybeUninit::new(bool::default()),
                    unique_type: std::mem::MaybeUninit::new(uniqueness::default()),
                }
            }
        }
        #[derive(Debug, Copy, Clone, Default, PartialEq, Eq)]
        #[repr(u32)]
        pub enum uniqueness {
            #[default]
            UNQ_OFF = 0,
            UNQ_PID = 1,
            UNQ_CGROUP = 2,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub tgid: u32,
            pub pid: i32,
            pub uid: u32,
            pub cap: i32,
            pub audit: i32,
            pub insetid: i32,
            pub comm: [u8; 16],
            pub kernel_stack_id: i32,
            pub user_stack_id: i32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {
            pub tool_config: __anon_5,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub _event: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub events: __anon_1,
            pub seen: __anon_2,
        }
    }
    pub struct OpenCapableSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenCapableMaps<'obj>,
        pub progs: OpenCapableProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenCapableSkel<'obj> {
        type Output = CapableSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<CapableSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(CapableSkel {
                maps: unsafe { CapableMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: CapableProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: CapableLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct CapableLinks {
        pub kprobe__cap_capable: Option<libbpf_rs::Link>,
    }
    pub struct CapableSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: CapableMaps<'obj>,
        pub progs: CapableProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: CapableLinks,
    }

    unsafe impl Send for CapableSkel<'_> {}
    unsafe impl Sync for CapableSkel<'_> {}

    impl<'obj> Skel<'obj> for CapableSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = CapableLinks {
                kprobe__cap_capable: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl CapableSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 107, 112, 114, 111, 98, 101, 47, 99, 97, 112, 95, 99, 97, 112, 97, 98, 108, 101, 0,
        46, 114, 111, 100, 97, 116, 97, 0, 46, 98, 115, 115, 0, 108, 105, 99, 101, 110, 115, 101,
        0, 46, 109, 97, 112, 115, 0, 99, 97, 112, 97, 98, 108, 101, 46, 98, 112, 102, 46, 99, 0,
        107, 112, 114, 111, 98, 101, 95, 95, 99, 97, 112, 95, 99, 97, 112, 97, 98, 108, 101, 0,
        116, 111, 111, 108, 95, 99, 111, 110, 102, 105, 103, 0, 95, 101, 118, 101, 110, 116, 0, 76,
        73, 67, 69, 78, 83, 69, 0, 101, 118, 101, 110, 116, 115, 0, 115, 101, 101, 110, 0, 46, 66,
        84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 77, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 97, 0, 0, 0,
        17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 109, 0, 0, 0, 17, 0, 5, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 116, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 124, 0, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0,
        0, 0, 0, 0, 0, 131, 0, 0, 0, 17, 0, 7, 0, 24, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 71,
        80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159,
        235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 156, 5, 0, 0, 156, 5, 0, 0, 216, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 4, 24, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30,
        0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 39, 0, 0, 0, 1, 0, 0, 0, 128, 0, 0, 0, 50, 0, 0, 0, 0, 0,
        0, 14, 5, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        12, 0, 0, 0, 57, 0, 0, 0, 3, 0, 0, 4, 16, 0, 0, 0, 68, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 72,
        0, 0, 0, 13, 0, 0, 0, 32, 0, 0, 0, 77, 0, 0, 0, 16, 0, 0, 0, 64, 0, 0, 0, 86, 0, 0, 0, 0,
        0, 0, 8, 14, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 1, 4, 0,
        0, 0, 32, 0, 0, 0, 109, 0, 0, 0, 0, 0, 0, 8, 17, 0, 0, 0, 113, 0, 0, 0, 0, 0, 0, 8, 18, 0,
        0, 0, 119, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 16, 0, 0,
        0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 138, 0, 0, 0,
        9, 0, 0, 0, 64, 0, 0, 0, 150, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0, 154, 0, 0, 0, 19, 0, 0,
        0, 192, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 14, 20, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 23, 0, 0, 0, 165, 0, 0, 0, 9, 0, 0, 4, 80, 1, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0,
        173, 0, 0, 0, 16, 0, 0, 0, 128, 8, 0, 0, 181, 0, 0, 0, 29, 0, 0, 0, 192, 8, 0, 0, 191, 0,
        0, 0, 13, 0, 0, 0, 224, 8, 0, 0, 199, 0, 0, 0, 16, 0, 0, 0, 0, 9, 0, 0, 210, 0, 0, 0, 16,
        0, 0, 0, 64, 9, 0, 0, 219, 0, 0, 0, 31, 0, 0, 0, 128, 9, 0, 0, 230, 0, 0, 0, 16, 0, 0, 0,
        0, 10, 0, 0, 247, 0, 0, 0, 16, 0, 0, 0, 64, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 16, 1, 0, 0,
        0, 1, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 10, 1, 0, 0, 4,
        0, 0, 4, 16, 1, 0, 0, 23, 1, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 28, 1, 0, 0, 17, 0, 0, 0, 192,
        7, 0, 0, 31, 1, 0, 0, 17, 0, 0, 0, 0, 8, 0, 0, 34, 1, 0, 0, 17, 0, 0, 0, 64, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 17, 0, 0, 0, 4, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4,
        16, 1, 0, 0, 23, 1, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 28, 1, 0, 0, 16, 0, 0, 0, 192, 7, 0, 0,
        31, 1, 0, 0, 16, 0, 0, 0, 0, 8, 0, 0, 34, 1, 0, 0, 16, 0, 0, 0, 64, 8, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0, 31, 0, 0, 0, 41, 1, 0, 0, 0, 0, 0, 8, 30, 0,
        0, 0, 45, 1, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 16, 0, 0, 0,
        4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 51, 1, 0, 0, 22, 0, 0, 0, 55,
        1, 0, 0, 1, 0, 0, 12, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 9, 36, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 4, 12, 0, 0, 0, 72, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0,
        0, 75, 1, 0, 0, 39, 0, 0, 0, 32, 0, 0, 0, 83, 1, 0, 0, 41, 0, 0, 0, 64, 0, 0, 0, 95, 1, 0,
        0, 0, 0, 0, 8, 38, 0, 0, 0, 101, 1, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 118, 1, 0, 0, 0, 0, 0,
        8, 40, 0, 0, 0, 123, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 4, 129, 1, 0, 0, 3, 0, 0, 6,
        4, 0, 0, 0, 140, 1, 0, 0, 0, 0, 0, 0, 148, 1, 0, 0, 1, 0, 0, 0, 156, 1, 0, 0, 2, 0, 0, 0,
        167, 1, 0, 0, 0, 0, 0, 14, 34, 0, 0, 0, 1, 0, 0, 0, 179, 1, 0, 0, 9, 0, 0, 4, 48, 0, 0, 0,
        72, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 185, 1, 0, 0, 44, 0, 0, 0, 32, 0, 0, 0, 189, 1, 0, 0,
        46, 0, 0, 0, 64, 0, 0, 0, 68, 0, 0, 0, 2, 0, 0, 0, 96, 0, 0, 0, 193, 1, 0, 0, 2, 0, 0, 0,
        128, 0, 0, 0, 199, 1, 0, 0, 2, 0, 0, 0, 160, 0, 0, 0, 207, 1, 0, 0, 51, 0, 0, 0, 192, 0, 0,
        0, 212, 1, 0, 0, 2, 0, 0, 0, 64, 1, 0, 0, 228, 1, 0, 0, 2, 0, 0, 0, 96, 1, 0, 0, 242, 1, 0,
        0, 0, 0, 0, 8, 45, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 7, 2, 0, 0, 0, 0, 0, 8,
        47, 0, 0, 0, 13, 2, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 30, 2, 0, 0, 0, 0, 0, 8, 49, 0, 0, 0,
        33, 2, 0, 0, 0, 0, 0, 8, 50, 0, 0, 0, 38, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 48, 0, 0, 0, 4, 0, 0, 0, 16, 0, 0, 0, 52, 2, 0, 0, 0, 0,
        0, 14, 43, 0, 0, 0, 1, 0, 0, 0, 59, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 53, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 64, 2, 0, 0, 0, 0, 0, 14,
        54, 0, 0, 0, 1, 0, 0, 0, 170, 2, 0, 0, 1, 0, 0, 15, 12, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 0,
        12, 0, 0, 0, 178, 2, 0, 0, 1, 0, 0, 15, 48, 0, 0, 0, 52, 0, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0,
        183, 2, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 55, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 191, 2, 0, 0,
        2, 0, 0, 15, 56, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 21, 0, 0, 0, 24, 0, 0, 0,
        32, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84,
        89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0, 107, 101, 121, 95, 115, 105, 122, 101, 0,
        118, 97, 108, 117, 101, 95, 115, 105, 122, 101, 0, 101, 118, 101, 110, 116, 115, 0, 117,
        110, 105, 113, 117, 101, 95, 107, 101, 121, 0, 99, 97, 112, 0, 116, 103, 105, 100, 0, 99,
        103, 114, 111, 117, 112, 105, 100, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110,
        115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 117, 54, 52, 0, 95, 95, 117, 54, 52, 0,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0,
        109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108,
        117, 101, 0, 115, 101, 101, 110, 0, 112, 116, 95, 114, 101, 103, 115, 0, 111, 114, 105,
        103, 95, 120, 48, 0, 115, 121, 115, 99, 97, 108, 108, 110, 111, 0, 117, 110, 117, 115, 101,
        100, 50, 0, 115, 100, 101, 105, 95, 116, 116, 98, 114, 49, 0, 112, 109, 114, 95, 115, 97,
        118, 101, 0, 115, 116, 97, 99, 107, 102, 114, 97, 109, 101, 0, 108, 111, 99, 107, 100, 101,
        112, 95, 104, 97, 114, 100, 105, 114, 113, 115, 0, 101, 120, 105, 116, 95, 114, 99, 117, 0,
        117, 115, 101, 114, 95, 114, 101, 103, 115, 0, 117, 115, 101, 114, 95, 112, 116, 95, 114,
        101, 103, 115, 0, 114, 101, 103, 115, 0, 115, 112, 0, 112, 99, 0, 112, 115, 116, 97, 116,
        101, 0, 115, 51, 50, 0, 95, 95, 115, 51, 50, 0, 99, 116, 120, 0, 107, 112, 114, 111, 98,
        101, 95, 95, 99, 97, 112, 95, 99, 97, 112, 97, 98, 108, 101, 0, 118, 101, 114, 98, 111,
        115, 101, 0, 117, 110, 105, 113, 117, 101, 95, 116, 121, 112, 101, 0, 103, 105, 100, 95,
        116, 0, 95, 95, 107, 101, 114, 110, 101, 108, 95, 103, 105, 100, 51, 50, 95, 116, 0, 98,
        111, 111, 108, 0, 95, 66, 111, 111, 108, 0, 117, 110, 105, 113, 117, 101, 110, 101, 115,
        115, 0, 85, 78, 81, 95, 79, 70, 70, 0, 85, 78, 81, 95, 80, 73, 68, 0, 85, 78, 81, 95, 67,
        71, 82, 79, 85, 80, 0, 116, 111, 111, 108, 95, 99, 111, 110, 102, 105, 103, 0, 101, 118,
        101, 110, 116, 0, 112, 105, 100, 0, 117, 105, 100, 0, 97, 117, 100, 105, 116, 0, 105, 110,
        115, 101, 116, 105, 100, 0, 99, 111, 109, 109, 0, 107, 101, 114, 110, 101, 108, 95, 115,
        116, 97, 99, 107, 95, 105, 100, 0, 117, 115, 101, 114, 95, 115, 116, 97, 99, 107, 95, 105,
        100, 0, 112, 105, 100, 95, 116, 0, 95, 95, 107, 101, 114, 110, 101, 108, 95, 112, 105, 100,
        95, 116, 0, 117, 105, 100, 95, 116, 0, 95, 95, 107, 101, 114, 110, 101, 108, 95, 117, 105,
        100, 51, 50, 95, 116, 0, 117, 56, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 99, 104, 97, 114, 0, 95, 101, 118, 101, 110, 116, 0, 99, 104, 97, 114, 0, 76, 73,
        67, 69, 78, 83, 69, 0, 47, 104, 111, 109, 101, 47, 107, 120, 120, 116, 47, 114, 101, 112,
        111, 115, 47, 108, 105, 98, 98, 112, 102, 45, 115, 121, 115, 45, 49, 48, 54, 45, 114, 101,
        112, 114, 111, 47, 115, 114, 99, 47, 98, 112, 102, 47, 99, 97, 112, 97, 98, 108, 101, 46,
        98, 112, 102, 46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82, 79, 66, 69, 40,
        107, 112, 114, 111, 98, 101, 95, 95, 99, 97, 112, 95, 99, 97, 112, 97, 98, 108, 101, 41,
        32, 123, 0, 46, 114, 111, 100, 97, 116, 97, 0, 46, 98, 115, 115, 0, 108, 105, 99, 101, 110,
        115, 101, 0, 46, 109, 97, 112, 115, 0, 107, 112, 114, 111, 98, 101, 47, 99, 97, 112, 95,
        99, 97, 112, 97, 98, 108, 101, 0, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20,
        0, 0, 0, 20, 0, 0, 0, 28, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 197, 2, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 33, 0, 0, 0, 16, 0, 0, 0, 197, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 72, 2, 0,
        0, 132, 2, 0, 0, 5, 152, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0,
        0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 1, 0, 0, 0, 0, 0, 0, 16, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36,
        0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 1, 0, 0, 0, 0, 0,
        0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 44, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 204, 1,
        0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 204, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 0, 140, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 141, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 10, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
